version: '2'

services:
  package:
    image: tcds-io/orm
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    tty: true

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    ports:
      - '3306:3306'
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
